### ISSUE TITLE
New Resource: Ability to update the existing VMkernel NIC (vmk*) interface

### ISSUE THREAD

**Issue by jatinpurohit92** [vmware/dscr-for-vmware#312]
Use Case:

- Ability to Update existing VMkernel Interface Port Settings such as MTU, Enabled Services
- Ability to Update existing VMkernel Interface IPv4 Settings (Static/DHCP), SubNet Mask, Gateway 

We may need to have 2 mandatory properties vmk name and Portgroup Name to identify the correct Interface, For ex. 

`Get-VMHost |Select -First 1 |Get-VMHostNetworkAdapter |Where-Object -FilterScript { $_.PortGroupName -eq 'Management Network'}`

**Comment by dmilov** [comment]
[VMHostVssNic](https://github.com/vmware/dscr-for-vmware/wiki/VMHostVssNic) resource can be used for the purpose of updating existing VMKernelAdapter. The resource doesn't have a Nic Name parameter because the value is controlled by the VC. The resource relies on the fact there could be only one VMKernalAdapter in a PortGroup. So, the port group name identifies uniquely the VMKernel adapter and if such exists the resource updates its setting.

We realize the documentation doesn't clearly state that and probably leads to the confusion the Resource can only be used to add or remove an adapter. 
[Example2](https://github.com/vmware/dscr-for-vmware/wiki/VMHostVssNic#example-2) demonstrates updating an existing VMKernalNic settings.

I'm going to update the description of the resource in the docuymentation.

**Comment by dmilov** [comment]
Updated the description of the resource in the documentation.
